# Generated by Django 3.0.4 on 2020-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200413_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
