# Generated by Django 3.0.4 on 2020-04-24 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200424_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=32)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_verify',
                'managed': False,
            },
        ),
    ]
