# Generated by Django 3.0.4 on 2020-04-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=15)),
                ('no', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=64)),
                ('ward', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
    ]
