# Generated by Django 3.0.4 on 2020-05-06 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('link', models.CharField(blank=True, max_length=2083, null=True)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
    ]
