# Generated by Django 3.0.4 on 2020-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('percent', models.IntegerField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'promotion',
                'managed': False,
            },
        ),
    ]
