# Generated by Django 3.0.4 on 2020-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookcategorydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fee', models.DecimalField(decimal_places=4, max_digits=13)),
                ('created_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2083)),
                ('created_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField()),
                ('origin_quantity', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quantity_exists', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=13)),
                ('origin_price', models.DecimalField(decimal_places=4, max_digits=13)),
                ('description', models.TextField()),
                ('total_star', models.IntegerField(blank=True, null=True)),
                ('times_rated', models.IntegerField(blank=True, null=True)),
                ('stopped_date', models.DateTimeField(blank=True, null=True)),
                ('blocked_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('activated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merchandise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MerchandiseCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merchandise_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MerchandiseDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'merchandise_delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MerchandiseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'merchandise_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MerchandisePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merchandise_portfolio',
                'managed': False,
            },
        ),
    ]
