# Generated by Django 3.0.4 on 2020-05-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
