# Generated by Django 3.0.4 on 2020-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=4, max_digits=13)),
                ('total_price_alter_discount', models.DecimalField(decimal_places=4, max_digits=13)),
            ],
            options={
                'db_table': 'detail_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'history_order_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_delivery', models.DecimalField(decimal_places=4, max_digits=13)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'order_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=128)),
                ('fee', models.DecimalField(decimal_places=4, max_digits=13)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
